title: Roberto del Campo # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  IT professional since '98, I started in the R & D division in Amper Data. I have also worked in the support and development of HFCs networks,network security and since 2006 I work for the Autonomous Community of Murcia. I have been manager of communications unit for 6 years, managing voice and data communications. Currently working as manager in the telecommunications unit, whose mission is to promote and develop the Digital Transformation in Murcia area. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/robertodelcampo/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
